# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code
RUN yarn build

# Expose port if needed (though stdio)

# Runtime command
CMD ["node", "dist/server.js"]
